### ISSUE TITLE
Add Github workflow to build & test React app on merges to main.

### ISSUE THREAD

**Issue by ZachBaird** [ZachBaird/ReadRoulette#12]
Give this [article](https://dev.to/achukka/build-and-test-react-app-with-github-actions-2jb2) a brief read.

Add something similar in the `.github` directory of the repository. You may have to specify the `ReadRoulette.React/ReadRouletteClient directory` to get it to work properly.

This will allow us to catch easy mistakes on our PRs.

**Comment by JustWaveThings** [comment]
Closed by #13
